#!/usr/bin/env python3
# %CopyrightBegin%
#
# SPDX-License-Identifier: Apache-2.0
#
# Copyright 2026 Leandro Ostera <leandro@ostera.io>
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# %CopyrightEnd%

"""Inventory declared BIF dispatch surfaces; this is not an authority allowlist."""

import argparse
import difflib
from pathlib import Path
import re
import sys

BIFS = "erts/emulator/beam/bif.tab"
DIRTY = "erts/emulator/beam/erl_dirty_bif.tab"
MFA = re.compile(r"([a-z_0-9.']+):(.+)/(\d+)$")
DEFINITION = re.compile(r"\b(?:BIF_RETTYPE|Eterm)\s+(\w+)\s*\(\s*BIF_ALIST_\d+\s*\)"
                        r"(?:\s|/\*[\s\S]*?\*/)*\{")
HEADER = """# %CopyrightBegin%
#
# SPDX-License-Identifier: Apache-2.0
#
# Copyright 2026 Leandro Ostera <leandro@ostera.io>
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# %CopyrightEnd%
#
# Generated by scripts/realm-inventory.py --write; review changes before accepting.
# All entries are UNREVIEWED. Source locations are candidates, not authorization proof.
# Missing definitions can be macro/generated implementations; consult the surface ledger.
"""


def declarations(text, source, allowed):
    for number, line in enumerate(text.splitlines(), 1):
        stripped = line.strip()
        if not stripped or stripped.startswith("#"):
            continue
        fields = stripped.split()
        if fields[0] not in allowed or len(fields) not in (2, 3):
            raise ValueError(f"{source}:{number}: unsupported declaration: {stripped}")
        match = MFA.fullmatch(fields[1])
        if not match:
            raise ValueError(f"{source}:{number}: malformed MFA: {fields[1]}")
        yield fields, match.groups(), f"{source}:{number}"


def dispatch_rows(bif_text, dirty_text):
    dirty = {}
    for fields, _, anchor in declarations(dirty_text, DIRTY,
                                         {"dirty-cpu", "dirty-io", "dirty-cpu-test", "dirty-io-test"}):
        if len(fields) != 2 or fields[1] in dirty:
            raise ValueError(f"{anchor}: duplicate or unsupported dirty annotation")
        dirty[fields[1]] = (fields[0], anchor)
    rows = {}
    for fields, (module, name, arity), anchor in declarations(bif_text, BIFS, {"bif", "hbif", "ubif"}):
        kind, mfa = fields[:2]
        if mfa in rows:
            raise ValueError(f"{anchor}: duplicate MFA {mfa}")
        symbol = fields[2] if len(fields) == 3 else (
            ("" if module == "erlang" else module.strip("'") + "_") + name.strip("'") + "_" + arity)
        if not re.fullmatch(r"[A-Za-z_]\w*", symbol):
            raise ValueError(f"{anchor}: unsupported C symbol {symbol}")
        annotation, dirty_anchor = dirty.get(mfa, ("none", "none"))
        production = "normal"
        testing = "normal"
        # Match make_tables: ubif overrides dirty annotations in both modes.
        if kind != "ubif" and annotation != "none":
            testing = "dirty_cpu" if annotation.startswith("dirty-cpu") else "dirty_io"
            if not annotation.endswith("-test"):
                production = testing
        rows[mfa] = [mfa, kind, symbol, production, testing, annotation, anchor, dirty_anchor]
    unused = [(mfa, *value) for mfa, value in sorted(dirty.items()) if mfa not in rows]
    return [rows[mfa] for mfa in sorted(rows)], unused


def definitions(root):
    found = {}
    # Only source directories, not generated objects or native test fixtures.
    base = root / "erts/emulator"
    paths = sorted(set(base.glob("beam/*.c")) | set(base.glob("sys/*/*.c")) |
                   set(base.glob("drivers/*/*.c")))
    for path in paths:
        text = path.read_text()
        for match in DEFINITION.finditer(text):
            anchor = f"{path.relative_to(root).as_posix()}:{text.count(chr(10), 0, match.start()) + 1}"
            found.setdefault(match.group(1), []).append(anchor)
    return found


def inventory(root):
    rows, unused = dispatch_rows((root / BIFS).read_text(), (root / DIRTY).read_text())
    candidates = definitions(root)
    output = HEADER
    for mfa, kind, anchor in unused:
        output += f"# unmatched-dirty-annotation\t{mfa}\t{kind}\t{anchor}\n"
    output += "mfa\tkind\tc_symbol\tproduction_scheduler\tdirty_test_scheduler\tdirty_annotation\tdeclaration\tdirty_declaration\tdefinition_candidates\treview_status\n"
    for row in rows:
        output += "\t".join(row + [";".join(candidates.get(row[2], [])) or "unresolved", "UNREVIEWED"]) + "\n"
    return output


def nif_inventory(root):
    source = "erts/emulator/beam/erl_nif_api_funcs.h"
    return nif_declarations((root / source).read_text(), source)


def nif_declarations(text, source):
    output = HEADER[:HEADER.index("# Generated by")]
    output += "# Generated by scripts/realm-inventory.py --surface nif-api --write\n"
    output += "# ABI declaration order is preserved, including conditional declarations.\n"
    output += "# An ErlNifEnv parameter is NOT proof of a live caller or authority.\n"
    output += "ordinal\tc_symbol\treturn_type\tsignature\tenv_parameter_hint\tdeclaration\treview_status\n"
    seen = set()
    for number, line in enumerate(text.splitlines(), 1):
        line = line.strip()
        if not line.startswith("ERL_NIF_API_FUNC_DECL"):
            continue
        match = re.fullmatch(r"ERL_NIF_API_FUNC_DECL\(([^,]+),\s*(enif_\w+)\s*,(.+)\);", line)
        if not match or line.count("(") != line.count(")"):
            raise ValueError(f"{source}:{number}: unsupported NIF declaration grammar")
        result, symbol, signature = (value.strip() for value in match.groups())
        if symbol in seen:
            raise ValueError(f"{source}:{number}: duplicate NIF API {symbol}")
        seen.add(symbol)
        signature = " ".join(signature.split())
        hint = "present_not_authority" if re.search(r"\bErlNifEnv\s*\*", signature) else "absent"
        output += "\t".join([str(len(seen)), symbol, result, signature, hint,
                             f"{source}:{number}", "UNREVIEWED"]) + "\n"
    if not seen:
        raise ValueError("no NIF API declarations found")
    return output


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--root", type=Path, default=Path(__file__).resolve().parent.parent)
    mode = parser.add_mutually_exclusive_group(required=True)
    mode.add_argument("--check", action="store_true", help="fail if the recorded dispatch inventory drifted")
    mode.add_argument("--write", action="store_true", help="explicitly regenerate the source-fact inventory")
    parser.add_argument("--surface", choices=("bif", "nif-api"), default="bif")
    parser.add_argument("--output", type=Path, help="default: ROOT/../docs/rfds/0001-SURFACE-inventory.tsv (ROOT is beam/)")
    args = parser.parse_args()
    root = args.root.resolve()
    path = args.output or root.parent / f"docs/rfds/0001-{args.surface}-inventory.tsv"
    try:
        generated = inventory(root) if args.surface == "bif" else nif_inventory(root)
        if args.write:
            path.write_text(generated)
            print(f"Wrote {path}; no entries have been policy-reviewed.")
            return 0
        old = path.read_text() if path.exists() else ""
        if old != generated:
            for line in difflib.unified_diff(old.splitlines(), generated.splitlines(),
                                             fromfile=str(path), tofile="current source", lineterm=""):
                print(line)
            print("Inventory drift: review new/removed/changed dispatch surfaces and refresh explicitly.", file=sys.stderr)
            return 1
        count = sum(not line.startswith("#") for line in generated.splitlines()) - 1
        print(f"Dispatch inventory matches: {count} declarations; policy review remains open.")
        return 0
    except (OSError, ValueError) as error:
        print(error, file=sys.stderr)
        return 1


if __name__ == "__main__":
    sys.exit(main())
