#!/usr/bin/env python3
# SPDX-License-Identifier: Apache-2.0
# Copyright 2026 Leandro Ostera <leandro@ostera.io>
"""Run pinned OTP beam_makeops; project its immutable decoder/emitter metadata.

Hot/warm/cold dispatch and transformation bodies are retained as build artifacts,
not compiled behind no-op ERTS compatibility functions.
"""
import argparse
import hashlib
import json
import os
from pathlib import Path
import re
import subprocess
from project_transform import project
from project_dispatch import project as project_dispatch


def main():
    p = argparse.ArgumentParser(description=__doc__)
    p.add_argument('--output', type=Path, required=True)
    p.add_argument('--perl', default='perl')
    args = p.parse_args()
    root = Path(__file__).resolve().parents[1]
    base = root / 'core/otp/opcodes'
    generator = root / 'tools/otp/beam_makeops'
    manifest = json.loads((base / 'manifest.json').read_text())
    if manifest['profile'] != {'wordsize': 64, 'jit': 'no', 'USE_VM_PROBES': 0}:
        raise RuntimeError('Only the admitted 64-bit interpreter generation profile is supported')
    def check(path, expected):
        if hashlib.sha256(path.read_bytes()).hexdigest() != expected:
            raise RuntimeError(f'Unreviewed opcode input: {path}')
    check(generator, manifest['generator_sha256'])
    for entry in manifest['inputs']:
        check(base / entry['input'], entry['sha256'])
    output = args.output.resolve()
    output.mkdir(parents=True, exist_ok=True)
    upstream = output / 'upstream'
    upstream.mkdir(exist_ok=True)
    subprocess.run([args.perl, str(generator), '-wordsize', '64', '-jit', 'no',
                    '-DUSE_VM_PROBES=0', '-outdir', str(upstream), '-emulator',
                    *[e['input'] for e in manifest['inputs']]], cwd=base,
                   env={**os.environ, 'LANG': 'C'}, check=True)
    text = (upstream / 'beam_opcodes.c').read_text()
    # Exact array bodies from the upstream generator. No independent opcode list,
    # arity parser, reordered instruction selection, or hand-numbered tags.
    arrays = []
    for typename, name in [('char', 'tag_to_letter'), ('OpEntry', 'opc'), ('GenOpEntry', 'gen_opc')]:
        matches = re.findall(r'const '+typename+r' '+name+r'\[\] = \{.*?\n\};', text, re.S)
        if len(matches) != 1: raise RuntimeError(f'Generator shape changed: {name}')
        arrays.append(matches[0])
    header = (upstream / 'beam_opcodes.h').read_text()
    notice = ('/* SPDX-License-Identifier: Apache-2.0\n'
              ' * Copyright Ericsson AB 1996-2026. All Rights Reserved.\n'
              ' * Generated by pinned beam_makeops. See core/otp/opcodes/manifest.json.\n */\n')
    (output / 'lb_opcodes_generated.h').write_text(notice + header)
    (output / 'lb_opcodes_generated.inc').write_text(notice + '\n'.join(arrays) + '\n')
    transform, admission = project(text)
    (output / 'lb_transform_generated.inc').write_text(notice + transform)
    (output / 'transform-admission.json').write_text(json.dumps(admission, indent=2)+'\n')
    dispatch, support = project_dispatch('\n'.join((upstream/name).read_text() for name in ('beam_hot.h','beam_warm.h','beam_cold.h')))
    (output / 'lb_dispatch_generated.inc').write_text(notice + dispatch)
    (output / 'lb_dispatch_support.inc').write_text(notice + support)
    hashes = {f.name: hashlib.sha256(f.read_bytes()).hexdigest() for f in sorted(upstream.iterdir()) if f.is_file()}
    (output / 'outputs.json').write_text(json.dumps(hashes, indent=2)+'\n')


if __name__ == '__main__':
    main()
