/* SPDX-License-Identifier: Apache-2.0
 * Copyright Ericsson AB 1996-2026. All Rights Reserved.
 * Copyright 2026 Leandro Ostera <leandro@ostera.io>
 * The engine body is generated by the admitted OTP beam_makeops. Only ownership,
 * fallible allocation and explicit unsupported-case exits are adapted.
 */
#include "code_internal.h"
BeamOp *lb_load_new_op(LoaderState *st)
{
    BeamOp *op;
    if(!st->free_ops) {
        BeamOp *block=lb_palloc(st->program,32,sizeof(*block)); size_t i;
        if(!block) return NULL;
        for(i=0;i<31;++i) block[i].next=&block[i+1];
        st->free_ops=block;
    }
    op=st->free_ops; st->free_ops=op->next;
    memset(op,0,sizeof(*op)); op->a=op->def_args;
    return op;
}
void lb_load_free_op(LoaderState *st,BeamOp *op)
{
    /* Expanded arrays remain owned by the preparation arena until destruction.
     * Reused operations never retain pointers into another operation's array. */
    op->next=st->free_ops; st->free_ops=op;
}
static int needs_nif_padding(LoaderState *st)
{
    Export *entry=lb_export_find(st->space,st->module,st->function,st->arity);
    /* NIF loading is not admitted. A real native catalog entry still needs its
     * native trampoline size; this is a lookup, not a missing-helper stub. */
    return entry && entry->bif_number>=0;
}
static int is_heavy_bif(LoaderState *st,BeamOpArg arg)
{
    if(arg.type!=TAG_u || arg.val<0 || (Uint)arg.val>=st->beam.imports.count) {
        st->status=LB_CODE_FORMAT; return 0;
    }
    return st->bif_imports[arg.val] && st->bif_imports[arg.val]->kind==BIF_KIND_HEAVY;
}
static int smp_already_locked(LoaderState *st,BeamOpArg arg)
{
    if(arg.type!=TAG_u || arg.val<=0 || (Uint)arg.val>=st->label_count) {
        st->status=LB_CODE_FORMAT; return 0;
    }
    return st->labels[arg.val].looprec_targeted;
}
static int smp_mark_target_label(LoaderState *st,BeamOpArg arg)
{
    if(arg.type!=TAG_f || arg.val<=0 || (Uint)arg.val>=st->label_count) {
        st->status=LB_CODE_FORMAT; return 0;
    }
    st->labels[arg.val].looprec_targeted=1; return 1;
}
/* beam_transform_helpers.c: sort operand/label pairs by the native word value.
 * Only arity headers are admitted by this generator's verifier. */
static int oparg_compare(const void *left,const void *right)
{
    const BeamOpArg *a=left,*b=right;
    if(a->val<b->val) return -1;
    if(a->val==b->val) return 0;
    return 1;
}
static void beam_load_sort_select_vals(BeamOpArg *base,size_t n)
{
    qsort(base,n,2*sizeof(BeamOpArg),oparg_compare);
}
#define bif_table (st->space->engine->bifs)
#define TR_REQUIRE(test) do { if(!(test)) return TE_BAD_FORMAT; } while(0)
/* Upstream generated helper parameters are intentionally uniform. */
#if defined(__clang__)
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wsign-compare"
#pragma clang diagnostic ignored "-Wunused-parameter"
#pragma clang diagnostic ignored "-Wunused-variable"
#pragma clang diagnostic ignored "-Wunused-but-set-variable"
#elif defined(__GNUC__)
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wsign-compare"
#pragma GCC diagnostic ignored "-Wunused-parameter"
#pragma GCC diagnostic ignored "-Wunused-variable"
#pragma GCC diagnostic ignored "-Wunused-but-set-variable"
#endif
#include "lb_transform_generated.inc"
#if defined(__clang__)
#pragma clang diagnostic pop
#elif defined(__GNUC__)
#pragma GCC diagnostic pop
#endif
int lb_transform(LoaderState *st) { return lb_transform_engine(st); }
